# true 1 和 false 0 
SerialNumber: "K69668543"
TopicName: "/right_camera/image"


width: 1024             #图像宽度
height: 800            #图像高度
#width: 3072             #图像宽度
#height: 2048            #图像高度
Offset_x: 30             #X方向偏置
Offset_y: 24             #Y方向偏置

FrameRateEnable: true   #使能 
FrameRate: 15           #帧率

ExposureTime: 5000     #曝光时间

GammaEnable: true
Gamma: 0.7              #伽马因子

GainAuto: 2             #亮度的固定增益

SaturationEnable: true
Saturation: 128          #饱和度
